# Generated by Django 3.1.7 on 2021-04-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormName', models.CharField(blank=True, max_length=100, null=True)),
                ('FormYear', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=500)),
                ('TaskDescription', models.TextField()),
                ('DueDate', models.DateField()),
                ('DateSet', models.DateTimeField(auto_now_add=True)),
                ('DateModified', models.DateTimeField(auto_now=True)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.classes')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.classes')),
                ('Form', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.form')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.classes')),
                ('StudentID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('TaskID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentContents', models.TextField()),
                ('PubOrPriv', models.CharField(choices=[('Pu', 'Public'), ('Pr', 'Private')], default='Pr', max_length=2)),
                ('Task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
