# Generated by Django 3.1.7 on 2021-04-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='StudentInClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.studentinclass'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='ClassName',
            field=models.CharField(max_length=100),
        ),
    ]
