# Generated by Django 3.1.7 on 2021-04-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210411_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='ClassID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='StudentInClass',
        ),
    ]
