# Generated by Django 3.1.7 on 2021-04-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Done',
        ),
        migrations.CreateModel(
            name='MarkDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Done', models.CharField(choices=[('Yes', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('StudentID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.studentuser')),
                ('TaskID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
