# Generated by Django 3.1.7 on 2021-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210412_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdone',
            name='Done',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Mark As Done', 'Mark As Done')], default='Mark As Done', max_length=500),
        ),
    ]
